class InsertValues < ActiveRecord::Migration[7.1]
  def change
    Player.create(name:'Player 1', age: 25,position: 'Forward',team_id: 1)
    Player.create(name:'Player 2', age: 30,position: 'Midfielder',team_id: 1)
    Player.create(name:'Player 3', age: 22,position: 'Defender',team_id: 2)
    Player.create(name:'Player 4', age: 27,position: 'Goalkeeper',team_id: 2)                                                  
    Player.create(name:'Player 5', age: 24,position: 'Forward',team_id: 3)                                                  
    Player.create(name:'Player 6', age: 29,position: 'Midfielder',team_id: 3)                                                  
    Player.create(name:'Player 7', age: 21,position: 'Defender',team_id: 4)                                                
    Player.create(name:'Player 8', age: 26,position: 'Goalkeeper',team_id: 4)                                                   
    Player.create(name:'Player 9', age: 23,position: 'Forward',team_id: 5)                                                   
    Player.create(name:'Player 10', age: 28,position: 'Midfielder',team_id: 5)                                                  
    Player.create(name:'Player 11', age: 31,position: 'Defender',team_id: 6)                                                   
    Player.create(name:'Player 12', age: 20,position: 'Goalkeeper',team_id: 6)                                                   
    Player.create(name:'Player 13', age: 22,position: 'Forward',team_id: 7)                                                  
    Player.create(name:'Player 14', age: 24,position: 'Midfielder',team_id: 7)                                                   
    Player.create(name:'Player 15', age: 26,position: 'Defender',team_id: 8)                                                  
    Player.create(name:'Player 16', age: 25,position: 'Goalkeeper',team_id: 8)                                                   
    Player.create(name:'Player 17', age: 29,position: 'Forward',team_id: 9)                                                  
    Player.create(name:'Player 18', age: 27,position: 'Midfielder',team_id: 9)                                                   
    Player.create(name:'Player 19', age: 21,position: 'Defender',team_id: 10)                                                   
    Player.create(name:'Player 20', age: 30,position: 'Goalkeeper',team_id: 10)                                                  
    Player.create(name:'Player 21', age: 23,position: 'Forward',team_id: 1)                                                   
    Player.create(name:'Player 22', age: 25,position: 'Midfielder',team_id: 2)                                                   
    Player.create(name:'Player 23', age: 28,position: 'Defender',team_id: 3)                                                  
    Player.create(name:'Player 24', age: 31,position: 'Goalkeeper',team_id: 4)                                                
    Player.create(name:'Player 25', age: 20,position: 'Forward',team_id: 5)                                                   
    Player.create(name:'Player 26', age: 22,position: 'Midfielder',team_id: 6)                                                   
    Player.create(name:'Player 27', age: 27,position: 'Defender',team_id: 7)                                                  
    Player.create(name:'Player 28', age: 29,position: 'Goalkeeper',team_id: 8)                                                   
    Player.create(name:'Player 29', age: 24,position: 'Forward',team_id: 9)                                                   
    Player.create(name:'Player 30', age: 26,position: 'Midfielder',team_id: 10)                                          
  end
end
